apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-jobservice
  namespace: harbor
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-registry
  namespace: harbor
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
